#!/usr/bin/env bash
#A script to print Best school 10 times and Hi on the 9th itereation
i=0
while [[ $i -lt 10 ]]; do
  echo "Best School"
if [[ $i -eq 8 ]]; then
  echo "Hi"
fi
  i="$((i + 1))"
done
