#!/usr/bin/env bash
#A script to display the time

hour=0
while [[ $hour -lt 13 ]]; do
  minute=1
  echo "Hour: $hour"
  while [[ $minute -lt 60 ]]; do
    echo "$minute"
    minute="$((minute + 1))"
  done
  hour="$((hour + 1))"
done
