#!/usr/bin/env bash
#A script to check if a file exist

file="school"
if test -a $file; then
  echo "$file file exists"
  if test -s $file; then
    echo "$file file is not empty"
  else
    echo "$file file is empty"
  fi
  if test -f $file; then
    echo "$file is a regular file"
  fi
else
  echo "$file file does not exist"
fi
